[versions]
minecraft = "1.21.1"
neoForge = "21.1.152"
registrate = "MC1.21-1.3.0+62"
clothConfig = "15.0.140"
anvilCraft = "1.4.11+build.1195"
curios = "9.0.15+1.21.1"
modDevGradle = "2.0.78"
lombok = "8.7.1"
machete = "1.+"

[libraries]
registrate = { group = "com.tterrag.registrate", name = "Registrate", version.ref = "registrate" }
clothConfig = { group = "me.shedaniel.cloth", name = "cloth-config-neoforge", version.ref = "clothConfig" }
anvilCraft = { group = "dev.dubhe", name = "anvilcraft-neoforge-1.21.1", version.ref = "anvilCraft" }
curios = { group = "top.theillusivec4.curios", name = "curios-neoforge", version.ref = "curios" }

[plugins]
modDevGradle = { id = "net.neoforged.moddev", version.ref = "modDevGradle" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }
machete = { id = "io.github.p03w.machete", version.ref = "machete" }
